// Generated by gencpp from file beginner_tutorials/BallLocation.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_BALLLOCATION_H
#define BEGINNER_TUTORIALS_MESSAGE_BALLLOCATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct BallLocation_
{
  typedef BallLocation_<ContainerAllocator> Type;

  BallLocation_()
    : bearing(0.0)
    , distance(0.0)  {
    }
  BallLocation_(const ContainerAllocator& _alloc)
    : bearing(0.0)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef double _bearing_type;
  _bearing_type bearing;

   typedef double _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::beginner_tutorials::BallLocation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::BallLocation_<ContainerAllocator> const> ConstPtr;

}; // struct BallLocation_

typedef ::beginner_tutorials::BallLocation_<std::allocator<void> > BallLocation;

typedef boost::shared_ptr< ::beginner_tutorials::BallLocation > BallLocationPtr;
typedef boost::shared_ptr< ::beginner_tutorials::BallLocation const> BallLocationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::BallLocation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::BallLocation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::BallLocation_<ContainerAllocator1> & lhs, const ::beginner_tutorials::BallLocation_<ContainerAllocator2> & rhs)
{
  return lhs.bearing == rhs.bearing &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::BallLocation_<ContainerAllocator1> & lhs, const ::beginner_tutorials::BallLocation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::BallLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::BallLocation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::BallLocation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e6b9899956f1eacd3991a6d711941249";
  }

  static const char* value(const ::beginner_tutorials::BallLocation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe6b9899956f1eacdULL;
  static const uint64_t static_value2 = 0x3991a6d711941249ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/BallLocation";
  }

  static const char* value(const ::beginner_tutorials::BallLocation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 bearing\n"
"float64 distance\n"
;
  }

  static const char* value(const ::beginner_tutorials::BallLocation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bearing);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BallLocation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::BallLocation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::BallLocation_<ContainerAllocator>& v)
  {
    s << indent << "bearing: ";
    Printer<double>::stream(s, indent + "  ", v.bearing);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_BALLLOCATION_H
